/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) double_integrator_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = {4, 4, 0, 0, 0, 1, 2, 0, 1};
static const casadi_int casadi_s1[9] = {4, 4, 0, 1, 2, 2, 2, 2, 3};
static const casadi_int casadi_s2[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s3[7] = {4, 2, 0, 1, 2, 2, 3};
static const casadi_int casadi_s4[9] = {2, 4, 0, 0, 0, 1, 2, 0, 1};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s6[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s7[3] = {0, 0, 0};
static const casadi_int casadi_s8[3] = {4, 0, 0};

/* double_integrator_impl_dae_jac_x_xdot_u_z:(i0[4],i1[4],i2[2],i3[],i4[],i5[])->(o0[4x4,2nz],o1[4x4,4nz],o2[4x2,2nz],o3[4x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+2, *w2=w+6, *w5=w+8, *w6=w+10, w7, w8;
  /* #0: @0 = zeros(4x4,2nz) */
  casadi_clear(w0, 2);
  /* #1: @1 = ones(4x1) */
  casadi_fill(w1, 4, 1.);
  /* #2: {NULL, @2} = vertsplit(@1) */
  casadi_copy(w1+2, 2, w2);
  /* #3: @3 = 00 */
  /* #4: @4 = 00 */
  /* #5: @5 = vertcat(@2, @3, @4) */
  rr=w5;
  for (i=0, cs=w2; i<2; ++i) *rr++ = *cs++;
  /* #6: @5 = (-@5) */
  for (i=0, rr=w5, cs=w5; i<2; ++i) *rr++ = (- *cs++ );
  /* #7: @2 = @5[:2] */
  for (rr=w2, ss=w5+0; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #8: (@0[:2] = @2) */
  for (rr=w0+0, ss=w2; rr!=w0+2; rr+=1) *rr = *ss++;
  /* #9: @2 = @0' */
  casadi_trans(w0,casadi_s1, w2, casadi_s0, iw);
  /* #10: output[0][0] = @2 */
  casadi_copy(w2, 2, res[0]);
  /* #11: @1 = zeros(4x4,4nz) */
  casadi_clear(w1, 4);
  /* #12: @6 = ones(4x1) */
  casadi_fill(w6, 4, 1.);
  /* #13: (@1[:4] = @6) */
  for (rr=w1+0, ss=w6; rr!=w1+4; rr+=1) *rr = *ss++;
  /* #14: @6 = @1' */
  casadi_trans(w1,casadi_s2, w6, casadi_s2, iw);
  /* #15: output[1][0] = @6 */
  casadi_copy(w6, 4, res[1]);
  /* #16: @2 = zeros(2x4,2nz) */
  casadi_clear(w2, 2);
  /* #17: @3 = zeros(2x1,0nz) */
  /* #18: @0 = ones(2x1) */
  casadi_fill(w0, 2, 1.);
  /* #19: {@7, @8} = vertsplit(@0) */
  w7 = w0[0];
  w8 = w0[1];
  /* #20: @0 = vertcat(@3, @7, @8) */
  rr=w0;
  *rr++ = w7;
  *rr++ = w8;
  /* #21: @0 = (-@0) */
  for (i=0, rr=w0, cs=w0; i<2; ++i) *rr++ = (- *cs++ );
  /* #22: @5 = @0[:2] */
  for (rr=w5, ss=w0+0; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #23: (@2[:2] = @5) */
  for (rr=w2+0, ss=w5; rr!=w2+2; rr+=1) *rr = *ss++;
  /* #24: @5 = @2' */
  casadi_trans(w2,casadi_s4, w5, casadi_s3, iw);
  /* #25: output[2][0] = @5 */
  casadi_copy(w5, 2, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int double_integrator_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int double_integrator_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int double_integrator_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void double_integrator_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int double_integrator_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void double_integrator_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void double_integrator_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void double_integrator_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int double_integrator_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int double_integrator_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real double_integrator_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_integrator_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_integrator_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_integrator_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s7;
    case 5: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_integrator_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int double_integrator_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 5;
  if (sz_w) *sz_w = 16;
  return 0;
}

CASADI_SYMBOL_EXPORT int double_integrator_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 5*sizeof(casadi_int);
  if (sz_w) *sz_w = 16*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
